### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by popov895** [comment]
Thanks! Can you also localize the `Name`, `Description` and `Keywords` in the [`metadata.desktop`](https://github.com/popov895/pminhibition/blob/main/metadata.desktop)?

**Comment by Vistaus** [comment]
Done! :)

**Comment by popov895** [comment]
And, please, create a new branch for pull requests. This will make it easier to keep the `main` branch of your fork in sync with the `main` branch of the parent repository. See [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for details.

**Comment by Vistaus** [comment]
That used to be the case, but there's a sync button since a long time in the GitHub UI that automatically keeps the fork in sync, so that's not necessary anymore.

**Comment by popov895** [comment]
I merged your PR by squashing the commits, so I guess there may be a conflict in syncing your fork with the parent repository.

**Comment by Vistaus** [comment]
Hmm, that's the first time I've ever heard that, and I've been doing it this way for a long time now with many devs. Maybe a branch could come in handy, but I need to look into how to work with those. Not sure if I want that. I'm just a translator and with so many projects to keep up with (both professionally as well as projects like this in my spare time), I'm not sure that's worth the hassle for me.

**Pull request merged**
